import type { Theme } from './types';

export const arcticDark: Theme = {
  id: 'arctic-dark',
  name: 'Arctic Dark',
  colors: {
    background: '#0a0f14',
    foreground: '#e0f2f1',
    primary: '#4dd0e1',
    primaryForeground: '#0a0f14',
    secondary: '#80cbc4',
    secondaryForeground: '#0a0f14',
    accent: '#15222e',
    accentForeground: '#e0f2f1',
    card: '#15222e',
    cardForeground: '#e0f2f1',
    popover: '#15222e',
    popoverForeground: '#e0f2f1',
    muted: '#1b2d3d',
    mutedForeground: '#78909c',
    destructive: '#ff5252',
    destructiveForeground: '#ffffff',
    border: '#263238',
    input: '#15222e',
    ring: '#4dd0e1',
    chart1: '#4dd0e1',
    chart2: '#80cbc4',
    chart3: '#b2ebf2',
    chart4: '#00bcd4',
    chart5: '#00838f',
    sidebar: '#070a0e',
    sidebarForeground: '#e0f2f1',
    sidebarPrimary: '#4dd0e1',
    sidebarPrimaryForeground: '#0a0f14',
    sidebarAccent: '#15222e',
    sidebarAccentForeground: '#e0f2f1',
    sidebarBorder: '#263238',
    sidebarRing: '#4dd0e1',
    fontSans: '"Geist Sans", sans-serif',
    fontSerif: 'Georgia, serif',
    fontMono: '"Geist Mono", monospace',
  }
};

export const arcticLight: Theme = {
  id: 'arctic-light',
  name: 'Arctic Light',
  colors: {
    background: '#f0faff',
    foreground: '#01579b',
    primary: '#00b8d4',
    primaryForeground: '#ffffff',
    secondary: '#0097a7',
    secondaryForeground: '#ffffff',
    accent: '#e1f5fe',
    accentForeground: '#01579b',
    card: '#ffffff',
    cardForeground: '#01579b',
    popover: '#ffffff',
    popoverForeground: '#01579b',
    muted: '#e1f5fe',
    mutedForeground: '#0288d1',
    destructive: '#d32f2f',
    destructiveForeground: '#ffffff',
    border: '#b3e5fc',
    input: '#ffffff',
    ring: '#00b8d4',
    chart1: '#00b8d4',
    chart2: '#0097a7',
    chart3: '#00acc1',
    chart4: '#0277bd',
    chart5: '#01579b',
    sidebar: '#e1f5fe',
    sidebarForeground: '#01579b',
    sidebarPrimary: '#00b8d4',
    sidebarPrimaryForeground: '#ffffff',
    sidebarAccent: '#b3e5fc',
    sidebarAccentForeground: '#01579b',
    sidebarBorder: '#81d4fa',
    sidebarRing: '#00b8d4',
    fontSans: '"Geist Sans", sans-serif',
    fontSerif: 'Georgia, serif',
    fontMono: '"Geist Mono", monospace',
  }
};
