import type { Theme } from './types';

export const autumnDark: Theme = {
  id: 'autumn-dark',
  name: 'Autumn Dark',
  colors: {
    background: '#1a0d0a',
    foreground: '#fbe9e7',
    primary: '#d84315',
    primaryForeground: '#ffffff',
    secondary: '#ff8f00',
    secondaryForeground: '#1a0d0a',
    accent: '#2d1814',
    accentForeground: '#fbe9e7',
    card: '#2d1814',
    cardForeground: '#fbe9e7',
    popover: '#2d1814',
    popoverForeground: '#fbe9e7',
    muted: '#3d1f1a',
    mutedForeground: '#bf360c',
    destructive: '#c62828',
    destructiveForeground: '#ffffff',
    border: '#4a2822',
    input: '#2d1814',
    ring: '#d84315',
    chart1: '#d84315',
    chart2: '#ff8f00',
    chart3: '#ff6f00',
    chart4: '#f4511e',
    chart5: '#ef6c00',
    sidebar: '#130a08',
    sidebarForeground: '#fbe9e7',
    sidebarPrimary: '#d84315',
    sidebarPrimaryForeground: '#ffffff',
    sidebarAccent: '#2d1814',
    sidebarAccentForeground: '#fbe9e7',
    sidebarBorder: '#4a2822',
    sidebarRing: '#d84315',
    fontSans: '"Geist Sans", sans-serif',
    fontSerif: 'Georgia, serif',
    fontMono: '"Geist Mono", monospace',
  }
};

export const autumnLight: Theme = {
  id: 'autumn-light',
  name: 'Autumn Light',
  colors: {
    background: '#fff3e0',
    foreground: '#3e2723',
    primary: '#e64a19',
    primaryForeground: '#ffffff',
    secondary: '#ffa000',
    secondaryForeground: '#ffffff',
    accent: '#ffe0b2',
    accentForeground: '#3e2723',
    card: '#ffffff',
    cardForeground: '#3e2723',
    popover: '#ffffff',
    popoverForeground: '#3e2723',
    muted: '#ffe0b2',
    mutedForeground: '#bf360c',
    destructive: '#c62828',
    destructiveForeground: '#ffffff',
    border: '#ffccbc',
    input: '#ffffff',
    ring: '#e64a19',
    chart1: '#e64a19',
    chart2: '#ffa000',
    chart3: '#f4511e',
    chart4: '#ef6c00',
    chart5: '#ffb300',
    sidebar: '#ffe0b2',
    sidebarForeground: '#3e2723',
    sidebarPrimary: '#e64a19',
    sidebarPrimaryForeground: '#ffffff',
    sidebarAccent: '#fff3e0',
    sidebarAccentForeground: '#3e2723',
    sidebarBorder: '#ffb300',
    sidebarRing: '#e64a19',
    fontSans: '"Geist Sans", sans-serif',
    fontSerif: 'Georgia, serif',
    fontMono: '"Geist Mono", monospace',
  }
};
