import type { Theme } from './types';

export const deepSeaDark: Theme = {
  id: 'deepsea-dark',
  name: 'Deep Sea Dark',
  colors: {
    background: '#050a14',
    foreground: '#b2ebf2',
    primary: '#00acc1',
    primaryForeground: '#ffffff',
    secondary: '#00838f',
    secondaryForeground: '#ffffff',
    accent: '#0d1a2d',
    accentForeground: '#b2ebf2',
    card: '#0d1a2d',
    cardForeground: '#b2ebf2',
    popover: '#0d1a2d',
    popoverForeground: '#b2ebf2',
    muted: '#142640',
    mutedForeground: '#4db6ac',
    destructive: '#e53935',
    destructiveForeground: '#ffffff',
    border: '#1a3a5a',
    input: '#0d1a2d',
    ring: '#00acc1',
    chart1: '#00acc1',
    chart2: '#00838f',
    chart3: '#006064',
    chart4: '#004d40',
    chart5: '#002d32',
    sidebar: '#03060c',
    sidebarForeground: '#b2ebf2',
    sidebarPrimary: '#00acc1',
    sidebarPrimaryForeground: '#ffffff',
    sidebarAccent: '#0d1a2d',
    sidebarAccentForeground: '#b2ebf2',
    sidebarBorder: '#1a3a5a',
    sidebarRing: '#00acc1',
    fontSans: '"Geist Sans", sans-serif',
    fontSerif: 'Georgia, serif',
    fontMono: '"Geist Mono", monospace',
  }
};

export const deepSeaLight: Theme = {
  id: 'deepsea-light',
  name: 'Deep Sea Light',
  colors: {
    background: '#e0f7fa',
    foreground: '#004d40',
    primary: '#00838f',
    primaryForeground: '#ffffff',
    secondary: '#006064',
    secondaryForeground: '#ffffff',
    accent: '#b2ebf2',
    accentForeground: '#004d40',
    card: '#ffffff',
    cardForeground: '#004d40',
    popover: '#ffffff',
    popoverForeground: '#004d40',
    muted: '#b2ebf2',
    mutedForeground: '#00796b',
    destructive: '#c62828',
    destructiveForeground: '#ffffff',
    border: '#80deea',
    input: '#ffffff',
    ring: '#00838f',
    chart1: '#00838f',
    chart2: '#006064',
    chart3: '#004d40',
    chart4: '#00796b',
    chart5: '#0097a7',
    sidebar: '#b2ebf2',
    sidebarForeground: '#004d40',
    sidebarPrimary: '#00838f',
    sidebarPrimaryForeground: '#ffffff',
    sidebarAccent: '#80deea',
    sidebarAccentForeground: '#004d40',
    sidebarBorder: '#4dd0e1',
    sidebarRing: '#00838f',
    fontSans: '"Geist Sans", sans-serif',
    fontSerif: 'Georgia, serif',
    fontMono: '"Geist Mono", monospace',
  }
};
