import type { Theme } from './types';

export const desertDark: Theme = {
  id: 'desert-dark',
  name: 'Desert Dark',
  colors: {
    background: '#1a1410',
    foreground: '#ece0d1',
    primary: '#d4a373',
    primaryForeground: '#1a1410',
    secondary: '#997b66',
    secondaryForeground: '#ffffff',
    accent: '#2d241e',
    accentForeground: '#ece0d1',
    card: '#2d241e',
    cardForeground: '#ece0d1',
    popover: '#2d241e',
    popoverForeground: '#ece0d1',
    muted: '#3d3028',
    mutedForeground: '#997b66',
    destructive: '#bc4749',
    destructiveForeground: '#ffffff',
    border: '#4d3d33',
    input: '#2d241e',
    ring: '#d4a373',
    chart1: '#d4a373',
    chart2: '#997b66',
    chart3: '#a68a64',
    chart4: '#6b705c',
    chart5: '#3f4238',
    sidebar: '#140f0c',
    sidebarForeground: '#ece0d1',
    sidebarPrimary: '#d4a373',
    sidebarPrimaryForeground: '#1a1410',
    sidebarAccent: '#2d241e',
    sidebarAccentForeground: '#ece0d1',
    sidebarBorder: '#4d3d33',
    sidebarRing: '#d4a373',
    fontSans: '"Geist Sans", sans-serif',
    fontSerif: 'Georgia, serif',
    fontMono: '"Geist Mono", monospace',
  }
};

export const desertLight: Theme = {
  id: 'desert-light',
  name: 'Desert Light',
  colors: {
    background: '#fefae0',
    foreground: '#283618',
    primary: '#bc6c25',
    primaryForeground: '#ffffff',
    secondary: '#dda15e',
    secondaryForeground: '#ffffff',
    accent: '#faedcd',
    accentForeground: '#283618',
    card: '#ffffff',
    cardForeground: '#283618',
    popover: '#ffffff',
    popoverForeground: '#283618',
    muted: '#faedcd',
    mutedForeground: '#606c38',
    destructive: '#bc4749',
    destructiveForeground: '#ffffff',
    border: '#d4a373',
    input: '#ffffff',
    ring: '#bc6c25',
    chart1: '#bc6c25',
    chart2: '#dda15e',
    chart3: '#606c38',
    chart4: '#283618',
    chart5: '#a68a64',
    sidebar: '#faedcd',
    sidebarForeground: '#283618',
    sidebarPrimary: '#bc6c25',
    sidebarPrimaryForeground: '#ffffff',
    sidebarAccent: '#fefae0',
    sidebarAccentForeground: '#283618',
    sidebarBorder: '#dda15e',
    sidebarRing: '#bc6c25',
    fontSans: '"Geist Sans", sans-serif',
    fontSerif: 'Georgia, serif',
    fontMono: '"Geist Mono", monospace',
  }
};
