import type { Theme } from './types'; // Import the Theme type from the types module

// Dark version of the Futuristic Blue theme
const futuristicBlueDark: Theme = {
  id: 'futuristicBlue-dark',
  name: 'Futuristic Blue Dark',
  colors: {
    background: '#0a0d1a',
    foreground: '#e0e6f8',
    primary: '#536dfe',
    primaryForeground: '#ffffff',
    secondary: '#00e5ff',
    secondaryForeground: '#0a0d1a',
    accent: '#141a2e',
    accentForeground: '#e0e6f8',
    card: '#141a2e',
    cardForeground: '#e0e6f8',
    popover: '#141a2e',
    popoverForeground: '#e0e6f8',
    muted: '#1e243a',
    mutedForeground: '#8895b2',
    destructive: '#ff3b30',
    destructiveForeground: '#ffffff',
    border: '#1e243a',
    input: '#141a2e',
    ring: '#536dfe',
    chart1: '#536dfe',
    chart2: '#00e5ff',
    chart3: '#00ff7f',
    chart4: '#ffd700',
    chart5: '#6c47ff',
    sidebar: '#040a12',
    sidebarForeground: '#e0e6f8',
    sidebarPrimary: '#536dfe',
    sidebarPrimaryForeground: '#ffffff',
    sidebarAccent: '#141a2e',
    sidebarAccentForeground: '#e0e6f8',
    sidebarBorder: '#1e243a',
    sidebarRing: '#536dfe',
    fontSans: '"Geist Sans", sans-serif',
    fontSerif: 'Georgia, serif',
    fontMono: '"Geist Mono", monospace',
  }
};

const futuristicBlueLight: Theme = {
  id: 'futuristicBlue-light',
  name: 'Futuristic Blue Light',
  colors: {
    background: '#e0f7fa',
    foreground: '#0d1b2a',
    primary: '#536dfe',
    primaryForeground: '#ffffff',
    secondary: '#00e5ff',
    secondaryForeground: '#ffffff',
    accent: '#f0fbff',
    accentForeground: '#0d1b2a',
    card: '#ffffff',
    cardForeground: '#0d1b2a',
    popover: '#ffffff',
    popoverForeground: '#0d1b2a',
    muted: '#f0fbff',
    mutedForeground: '#6b7c8c',
    destructive: '#ff3b30',
    destructiveForeground: '#ffffff',
    border: '#cfd8dc',
    input: '#ffffff',
    ring: '#536dfe',
    chart1: '#536dfe',
    chart2: '#00e5ff',
    chart3: '#00ff7f',
    chart4: '#ffd700',
    chart5: '#6c47ff',
    sidebar: '#d0e9f2',
    sidebarForeground: '#0d1b2a',
    sidebarPrimary: '#536dfe',
    sidebarPrimaryForeground: '#ffffff',
    sidebarAccent: '#f0fbff',
    sidebarAccentForeground: '#0d1b2a',
    sidebarBorder: '#cfd8dc',
    sidebarRing: '#536dfe',
    fontSans: '"Geist Sans", sans-serif',
    fontSerif: 'Georgia, serif',
    fontMono: '"Geist Mono", monospace',
  }
}; // End of the Futuristic Blue Light theme

export { futuristicBlueDark, futuristicBlueLight }; // Export both dark and light theme variants for use in the application


