import type { Theme } from './types';

export const nebulaDark: Theme = {
  id: 'nebula-dark',
  name: 'Midnight Nebula Dark',
  colors: {
    background: '#0d021c',
    foreground: '#e1bee7',
    primary: '#7b1fa2',
    primaryForeground: '#ffffff',
    secondary: '#311b92',
    secondaryForeground: '#ffffff',
    accent: '#1a052e',
    accentForeground: '#e1bee7',
    card: '#1a052e',
    cardForeground: '#e1bee7',
    popover: '#1a052e',
    popoverForeground: '#e1bee7',
    muted: '#2a0a4a',
    mutedForeground: '#9575cd',
    destructive: '#f44336',
    destructiveForeground: '#ffffff',
    border: '#311b92',
    input: '#1a052e',
    ring: '#7b1fa2',
    chart1: '#7b1fa2',
    chart2: '#311b92',
    chart3: '#4527a0',
    chart4: '#6a1b9a',
    chart5: '#4a148c',
    sidebar: '#080111',
    sidebarForeground: '#e1bee7',
    sidebarPrimary: '#7b1fa2',
    sidebarPrimaryForeground: '#ffffff',
    sidebarAccent: '#1a052e',
    sidebarAccentForeground: '#e1bee7',
    sidebarBorder: '#311b92',
    sidebarRing: '#7b1fa2',
    fontSans: '"Geist Sans", sans-serif',
    fontSerif: 'Georgia, serif',
    fontMono: '"Geist Mono", monospace',
  }
};

export const nebulaLight: Theme = {
  id: 'nebula-light',
  name: 'Midnight Nebula Light',
  colors: {
    background: '#f3e5f5',
    foreground: '#4a148c',
    primary: '#9c27b0',
    primaryForeground: '#ffffff',
    secondary: '#673ab7',
    secondaryForeground: '#ffffff',
    accent: '#e1bee7',
    accentForeground: '#4a148c',
    card: '#ffffff',
    cardForeground: '#4a148c',
    popover: '#ffffff',
    popoverForeground: '#4a148c',
    muted: '#e1bee7',
    mutedForeground: '#7b1fa2',
    destructive: '#d32f2f',
    destructiveForeground: '#ffffff',
    border: '#ce93d8',
    input: '#ffffff',
    ring: '#9c27b0',
    chart1: '#9c27b0',
    chart2: '#673ab7',
    chart3: '#7b1fa2',
    chart4: '#4a148c',
    chart5: '#8e24aa',
    sidebar: '#e1bee7',
    sidebarForeground: '#4a148c',
    sidebarPrimary: '#9c27b0',
    sidebarPrimaryForeground: '#ffffff',
    sidebarAccent: '#d1c4e9',
    sidebarAccentForeground: '#4a148c',
    sidebarBorder: '#ba68c8',
    sidebarRing: '#9c27b0',
    fontSans: '"Geist Sans", sans-serif',
    fontSerif: 'Georgia, serif',
    fontMono: '"Geist Mono", monospace',
  }
};
