import type { Theme } from './types';

export const sunsetDark: Theme = {
  id: 'sunset-dark',
  name: 'Sunset Dark',
  colors: {
    background: '#1a0b16',
    foreground: '#fce4ec',
    primary: '#ff4081',
    primaryForeground: '#ffffff',
    secondary: '#ffab40',
    secondaryForeground: '#1a0b16',
    accent: '#2d1526',
    accentForeground: '#fce4ec',
    card: '#2d1526',
    cardForeground: '#fce4ec',
    popover: '#2d1526',
    popoverForeground: '#fce4ec',
    muted: '#3d1d33',
    mutedForeground: '#b388ff',
    destructive: '#ff5252',
    destructiveForeground: '#ffffff',
    border: '#4a233d',
    input: '#2d1526',
    ring: '#ff4081',
    chart1: '#ff4081',
    chart2: '#ffab40',
    chart3: '#7c4dff',
    chart4: '#ffd740',
    chart5: '#ff6e40',
    sidebar: '#140811',
    sidebarForeground: '#fce4ec',
    sidebarPrimary: '#ff4081',
    sidebarPrimaryForeground: '#ffffff',
    sidebarAccent: '#2d1526',
    sidebarAccentForeground: '#fce4ec',
    sidebarBorder: '#4a233d',
    sidebarRing: '#ff4081',
    fontSans: '"Geist Sans", sans-serif',
    fontSerif: 'Georgia, serif',
    fontMono: '"Geist Mono", monospace',
  }
};

export const sunsetLight: Theme = {
  id: 'sunset-light',
  name: 'Sunset Light',
  colors: {
    background: '#fff5f7',
    foreground: '#4a132c',
    primary: '#ff4081',
    primaryForeground: '#ffffff',
    secondary: '#ff9100',
    secondaryForeground: '#ffffff',
    accent: '#fce4ec',
    accentForeground: '#4a132c',
    card: '#ffffff',
    cardForeground: '#4a132c',
    popover: '#ffffff',
    popoverForeground: '#4a132c',
    muted: '#fce4ec',
    mutedForeground: '#880e4f',
    destructive: '#d32f2f',
    destructiveForeground: '#ffffff',
    border: '#f8bbd0',
    input: '#ffffff',
    ring: '#ff4081',
    chart1: '#ff4081',
    chart2: '#ff9100',
    chart3: '#6a1b9a',
    chart4: '#fbc02d',
    chart5: '#ef6c00',
    sidebar: '#fce4ec',
    sidebarForeground: '#4a132c',
    sidebarPrimary: '#ff4081',
    sidebarPrimaryForeground: '#ffffff',
    sidebarAccent: '#f8bbd0',
    sidebarAccentForeground: '#4a132c',
    sidebarBorder: '#f06292',
    sidebarRing: '#ff4081',
    fontSans: '"Geist Sans", sans-serif',
    fontSerif: 'Georgia, serif',
    fontMono: '"Geist Mono", monospace',
  }
};
