import type { Theme } from './types';

// --- Void Dark Rainbow Themes ---
// A collection of dark themes with main colors of the rainbow

// Red Variation
const voidDarkRedTheme: Theme = {
  id: 'voidDarkRed',
  name: 'Void Dark Red',
  colors: {
    background: '#000000',
    foreground: '#FFFFFF',
    primary: '#ef4444',
    primaryForeground: '#ffffff',
    secondary: '#6366f1',
    secondaryForeground: '#ffffff',
    accent: '#080808',
    accentForeground: '#FFFFFF',
    card: '#080808',
    cardForeground: '#FFFFFF',
    popover: '#080808',
    popoverForeground: '#FFFFFF',
    muted: '#101010',
    mutedForeground: '#888888',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#1f1f1f',
    input: '#080808',
    ring: '#ef4444',
    chart1: '#ef4444',
    chart2: '#6366f1',
    chart3: '#f87171',
    chart4: '#f59e0b',
    chart5: '#6c47ff',
    sidebar: '#030303',
    sidebarForeground: '#FFFFFF',
    sidebarPrimary: '#ef4444',
    sidebarPrimaryForeground: '#ffffff',
    sidebarAccent: '#080808',
    sidebarAccentForeground: '#FFFFFF',
    sidebarBorder: '#1f1f1f',
    sidebarRing: '#ef4444',
    fontSans: '"Geist Sans", sans-serif',
    fontSerif: 'Georgia, serif',
    fontMono: '"Geist Mono", monospace',
  }
};

const voidDarkOrangeTheme: Theme = {
  id: 'voidDarkOrange',
  name: 'Void Dark Orange',
  colors: {
    background: '#000000',
    foreground: '#FFFFFF',
    primary: '#f97316',
    primaryForeground: '#ffffff',
    secondary: '#6366f1',
    secondaryForeground: '#ffffff',
    accent: '#080808',
    accentForeground: '#FFFFFF',
    card: '#080808',
    cardForeground: '#FFFFFF',
    popover: '#080808',
    popoverForeground: '#FFFFFF',
    muted: '#101010',
    mutedForeground: '#888888',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#1f1f1f',
    input: '#080808',
    ring: '#f97316',
    chart1: '#f97316',
    chart2: '#6366f1',
    chart3: '#fb923c',
    chart4: '#f59e0b',
    chart5: '#6c47ff',
    sidebar: '#030303',
    sidebarForeground: '#FFFFFF',
    sidebarPrimary: '#f97316',
    sidebarPrimaryForeground: '#ffffff',
    sidebarAccent: '#080808',
    sidebarAccentForeground: '#FFFFFF',
    sidebarBorder: '#1f1f1f',
    sidebarRing: '#f97316',
    fontSans: '"Geist Sans", sans-serif',
    fontSerif: 'Georgia, serif',
    fontMono: '"Geist Mono", monospace',
  }
};

const voidDarkYellowTheme: Theme = {
  id: 'voidDarkYellow',
  name: 'Void Dark Yellow',
  colors: {
    background: '#000000',
    foreground: '#FFFFFF',
    primary: '#eab308',
    primaryForeground: '#000000',
    secondary: '#6366f1',
    secondaryForeground: '#ffffff',
    accent: '#080808',
    accentForeground: '#FFFFFF',
    card: '#080808',
    cardForeground: '#FFFFFF',
    popover: '#080808',
    popoverForeground: '#FFFFFF',
    muted: '#101010',
    mutedForeground: '#888888',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#1f1f1f',
    input: '#080808',
    ring: '#eab308',
    chart1: '#eab308',
    chart2: '#6366f1',
    chart3: '#facc15',
    chart4: '#f59e0b',
    chart5: '#6c47ff',
    sidebar: '#030303',
    sidebarForeground: '#FFFFFF',
    sidebarPrimary: '#eab308',
    sidebarPrimaryForeground: '#000000',
    sidebarAccent: '#080808',
    sidebarAccentForeground: '#FFFFFF',
    sidebarBorder: '#1f1f1f',
    sidebarRing: '#eab308',
    fontSans: '"Geist Sans", sans-serif',
    fontSerif: 'Georgia, serif',
    fontMono: '"Geist Mono", monospace',
  }
};

const voidDarkBlueTheme: Theme = {
  id: 'voidDarkBlue',
  name: 'Void Dark Blue',
  colors: {
    background: '#000000',
    foreground: '#FFFFFF',
    primary: '#3b82f6',
    primaryForeground: '#ffffff',
    secondary: '#10b981',
    secondaryForeground: '#000000',
    accent: '#080808',
    accentForeground: '#FFFFFF',
    card: '#080808',
    cardForeground: '#FFFFFF',
    popover: '#080808',
    popoverForeground: '#FFFFFF',
    muted: '#101010',
    mutedForeground: '#888888',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#1f1f1f',
    input: '#080808',
    ring: '#3b82f6',
    chart1: '#3b82f6',
    chart2: '#10b981',
    chart3: '#60a5fa',
    chart4: '#f59e0b',
    chart5: '#6c47ff',
    sidebar: '#030303',
    sidebarForeground: '#FFFFFF',
    sidebarPrimary: '#3b82f6',
    sidebarPrimaryForeground: '#ffffff',
    sidebarAccent: '#080808',
    sidebarAccentForeground: '#FFFFFF',
    sidebarBorder: '#1f1f1f',
    sidebarRing: '#3b82f6',
    fontSans: '"Geist Sans", sans-serif',
    fontSerif: 'Georgia, serif',
    fontMono: '"Geist Mono", monospace',
  }
};

const voidDarkPurpleTheme: Theme = {
  id: 'voidDarkPurple',
  name: 'Void Dark Purple',
  colors: {
    background: '#000000',
    foreground: '#FFFFFF',
    primary: '#a855f7',
    primaryForeground: '#ffffff',
    secondary: '#10b981',
    secondaryForeground: '#000000',
    accent: '#080808',
    accentForeground: '#FFFFFF',
    card: '#080808',
    cardForeground: '#FFFFFF',
    popover: '#080808',
    popoverForeground: '#FFFFFF',
    muted: '#101010',
    mutedForeground: '#888888',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#1f1f1f',
    input: '#080808',
    ring: '#a855f7',
    chart1: '#a855f7',
    chart2: '#10b981',
    chart3: '#c084fc',
    chart4: '#f59e0b',
    chart5: '#6c47ff',
    sidebar: '#030303',
    sidebarForeground: '#FFFFFF',
    sidebarPrimary: '#a855f7',
    sidebarPrimaryForeground: '#ffffff',
    sidebarAccent: '#080808',
    sidebarAccentForeground: '#FFFFFF',
    sidebarBorder: '#1f1f1f',
    sidebarRing: '#a855f7',
    fontSans: '"Geist Sans", sans-serif',
    fontSerif: 'Georgia, serif',
    fontMono: '"Geist Mono", monospace',
  }
};

export {
  voidDarkRedTheme,
  voidDarkOrangeTheme,
  voidDarkYellowTheme,
  voidDarkBlueTheme,
  voidDarkPurpleTheme,
};


