import type { Theme } from './types';

// --- Void Dark Theme (Enhanced Darkness) ---
// An intensely dark theme using near-black and black backgrounds with high-contrast white text.
const voidDarkTheme: Theme = {
  id: 'voidDark',
  name: 'Void Dark',
  colors: {
    background: '#000000',
    foreground: '#FFFFFF',
    primary: '#6366f1',
    primaryForeground: '#ffffff',
    secondary: '#10b981',
    secondaryForeground: '#000000',
    accent: '#080808',
    accentForeground: '#FFFFFF',
    card: '#080808',
    cardForeground: '#FFFFFF',
    popover: '#080808',
    popoverForeground: '#FFFFFF',
    muted: '#101010',
    mutedForeground: '#888888',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#1f1f1f',
    input: '#080808',
    ring: '#6366f1',
    chart1: '#6366f1',
    chart2: '#10b981',
    chart3: '#818cf8',
    chart4: '#f59e0b',
    chart5: '#6c47ff',
    sidebar: '#030303',
    sidebarForeground: '#FFFFFF',
    sidebarPrimary: '#6366f1',
    sidebarPrimaryForeground: '#ffffff',
    sidebarAccent: '#080808',
    sidebarAccentForeground: '#FFFFFF',
    sidebarBorder: '#1f1f1f',
    sidebarRing: '#6366f1',
    fontSans: '"Geist Sans", sans-serif',
    fontSerif: 'Georgia, serif',
    fontMono: '"Geist Mono", monospace',
  }
};

const voidLightTheme: Theme = {
  id: 'voidLight',
  name: 'Void Light',
  colors: {
    background: '#FFFFFF',
    foreground: '#000000',
    primary: '#6366f1',
    primaryForeground: '#ffffff',
    secondary: '#10b981',
    secondaryForeground: '#ffffff',
    accent: '#F9F9F9',
    accentForeground: '#000000',
    card: '#FFFFFF',
    cardForeground: '#000000',
    popover: '#FFFFFF',
    popoverForeground: '#000000',
    muted: '#F9F9F9',
    mutedForeground: '#666666',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#EEEEEE',
    input: '#FFFFFF',
    ring: '#6366f1',
    chart1: '#6366f1',
    chart2: '#10b981',
    chart3: '#818cf8',
    chart4: '#f59e0b',
    chart5: '#6c47ff',
    sidebar: '#F0F0F0',
    sidebarForeground: '#000000',
    sidebarPrimary: '#6366f1',
    sidebarPrimaryForeground: '#ffffff',
    sidebarAccent: '#F9F9F9',
    sidebarAccentForeground: '#000000',
    sidebarBorder: '#EEEEEE',
    sidebarRing: '#6366f1',
    fontSans: '"Geist Sans", sans-serif',
    fontSerif: 'Georgia, serif',
    fontMono: '"Geist Mono", monospace',
  }
};

export { voidDarkTheme, voidLightTheme };


